### PR TITLE
upgrade to latest rollup and latest dependency versions

### PR DESCRIPTION
**Pull request by mnutt**
This just upgrades dependencies to the latest and updates tests to newer rollup config. 

No functional changes to the plugin itself, I was just having some trouble with the version of `rollup-pluginutils` that it depended on.

### CODE REVIEW

**Comment by mnutt** [comment]
Hi @bdadam, is this module still maintained?

**Comment by shellscape** [comment]
@mnutt we've put together https://www.npmjs.com/package/@rollup/plugin-html that's maintained out of the official [plugins repo](https://github.com/rollup/plugins).

**Comment by mnutt** [comment]
Thanks! 👍

**Comment by the-djmaze** [comment]
> @mnutt we've put together https://www.npmjs.com/package/@rollup/plugin-html

But it is not the same.

@bdadam version does:
```
import htmlFile from 'example.html';
```
And converts that into:
```
const htmlFile = "<html><body>this is the source of example.html</body></html>";
```

Yours does not...

**Pull request closed without merging**
